<?php
/**
 * AffiliateBlockObj
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * RevenueWire JackFruit REST API (Alpha)
 *
 * This API *does not* represent the final product. Some of the APIs listed below are *highly experimental* and *will likely change* before the final release. They may come with *crashes and bugs* and may potentially cause *data loss*.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;

/**
 * AffiliateBlockObj Class Doc Comment
 *
 * @category    Class
 * @description A block used to block affiliate sell merchant products
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AffiliateBlockObj implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'AffiliateBlockObj';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'blockId' => 'int',
        'affiliateId' => 'int',
        'affiliateFid' => 'string',
        'affiliateName' => 'string'
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'blockId' => 'blockId',
        'affiliateId' => 'affiliateId',
        'affiliateFid' => 'affiliateFid',
        'affiliateName' => 'affiliateName'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'blockId' => 'setBlockId',
        'affiliateId' => 'setAffiliateId',
        'affiliateFid' => 'setAffiliateFid',
        'affiliateName' => 'setAffiliateName'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'blockId' => 'getBlockId',
        'affiliateId' => 'getAffiliateId',
        'affiliateFid' => 'getAffiliateFid',
        'affiliateName' => 'getAffiliateName'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['blockId'] = isset($data['blockId']) ? $data['blockId'] : null;
        $this->container['affiliateId'] = isset($data['affiliateId']) ? $data['affiliateId'] : null;
        $this->container['affiliateFid'] = isset($data['affiliateFid']) ? $data['affiliateFid'] : null;
        $this->container['affiliateName'] = isset($data['affiliateName']) ? $data['affiliateName'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets blockId
     * @return int
     */
    public function getBlockId()
    {
        return $this->container['blockId'];
    }

    /**
     * Sets blockId
     * @param int $blockId
     * @return $this
     */
    public function setBlockId($blockId)
    {
        $this->container['blockId'] = $blockId;

        return $this;
    }

    /**
     * Gets affiliateId
     * @return int
     */
    public function getAffiliateId()
    {
        return $this->container['affiliateId'];
    }

    /**
     * Sets affiliateId
     * @param int $affiliateId
     * @return $this
     */
    public function setAffiliateId($affiliateId)
    {
        $this->container['affiliateId'] = $affiliateId;

        return $this;
    }

    /**
     * Gets affiliateFid
     * @return string
     */
    public function getAffiliateFid()
    {
        return $this->container['affiliateFid'];
    }

    /**
     * Sets affiliateFid
     * @param string $affiliateFid
     * @return $this
     */
    public function setAffiliateFid($affiliateFid)
    {
        $this->container['affiliateFid'] = $affiliateFid;

        return $this;
    }

    /**
     * Gets affiliateName
     * @return string
     */
    public function getAffiliateName()
    {
        return $this->container['affiliateName'];
    }

    /**
     * Sets affiliateName
     * @param string $affiliateName
     * @return $this
     */
    public function setAffiliateName($affiliateName)
    {
        $this->container['affiliateName'] = $affiliateName;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}


