<?php
/**
 * ConversionsDailyOrHourlyData
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * RevenueWire JackFruit REST API (Alpha)
 *
 * This API *does not* represent the final product. Some of the APIs listed below are *highly experimental* and *will likely change* before the final release. They may come with *crashes and bugs* and may potentially cause *data loss*.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;

/**
 * ConversionsDailyOrHourlyData Class Doc Comment
 *
 * @category    Class
 * @description Daily or hourly conversions summary data object
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ConversionsDailyOrHourlyData implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'ConversionsDailyOrHourlyData';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'clicks' => 'int',
        'conversionRate' => 'float',
        'conversions' => 'int',
        'date' => 'string',
        'fourteenDayAverage' => 'float',
        'payout' => 'float',
        'weekOverWeekAverage' => 'float'
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'clicks' => 'clicks',
        'conversionRate' => 'conversionRate',
        'conversions' => 'conversions',
        'date' => 'date',
        'fourteenDayAverage' => 'fourteenDayAverage',
        'payout' => 'payout',
        'weekOverWeekAverage' => 'weekOverWeekAverage'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'clicks' => 'setClicks',
        'conversionRate' => 'setConversionRate',
        'conversions' => 'setConversions',
        'date' => 'setDate',
        'fourteenDayAverage' => 'setFourteenDayAverage',
        'payout' => 'setPayout',
        'weekOverWeekAverage' => 'setWeekOverWeekAverage'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'clicks' => 'getClicks',
        'conversionRate' => 'getConversionRate',
        'conversions' => 'getConversions',
        'date' => 'getDate',
        'fourteenDayAverage' => 'getFourteenDayAverage',
        'payout' => 'getPayout',
        'weekOverWeekAverage' => 'getWeekOverWeekAverage'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['clicks'] = isset($data['clicks']) ? $data['clicks'] : null;
        $this->container['conversionRate'] = isset($data['conversionRate']) ? $data['conversionRate'] : null;
        $this->container['conversions'] = isset($data['conversions']) ? $data['conversions'] : null;
        $this->container['date'] = isset($data['date']) ? $data['date'] : null;
        $this->container['fourteenDayAverage'] = isset($data['fourteenDayAverage']) ? $data['fourteenDayAverage'] : null;
        $this->container['payout'] = isset($data['payout']) ? $data['payout'] : null;
        $this->container['weekOverWeekAverage'] = isset($data['weekOverWeekAverage']) ? $data['weekOverWeekAverage'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        if ($this->container['clicks'] === null) {
            $invalid_properties[] = "'clicks' can't be null";
        }
        if ($this->container['conversionRate'] === null) {
            $invalid_properties[] = "'conversionRate' can't be null";
        }
        if ($this->container['conversions'] === null) {
            $invalid_properties[] = "'conversions' can't be null";
        }
        if ($this->container['date'] === null) {
            $invalid_properties[] = "'date' can't be null";
        }
        if ($this->container['fourteenDayAverage'] === null) {
            $invalid_properties[] = "'fourteenDayAverage' can't be null";
        }
        if ($this->container['payout'] === null) {
            $invalid_properties[] = "'payout' can't be null";
        }
        if ($this->container['weekOverWeekAverage'] === null) {
            $invalid_properties[] = "'weekOverWeekAverage' can't be null";
        }
        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        if ($this->container['clicks'] === null) {
            return false;
        }
        if ($this->container['conversionRate'] === null) {
            return false;
        }
        if ($this->container['conversions'] === null) {
            return false;
        }
        if ($this->container['date'] === null) {
            return false;
        }
        if ($this->container['fourteenDayAverage'] === null) {
            return false;
        }
        if ($this->container['payout'] === null) {
            return false;
        }
        if ($this->container['weekOverWeekAverage'] === null) {
            return false;
        }
        return true;
    }


    /**
     * Gets clicks
     * @return int
     */
    public function getClicks()
    {
        return $this->container['clicks'];
    }

    /**
     * Sets clicks
     * @param int $clicks
     * @return $this
     */
    public function setClicks($clicks)
    {
        $this->container['clicks'] = $clicks;

        return $this;
    }

    /**
     * Gets conversionRate
     * @return float
     */
    public function getConversionRate()
    {
        return $this->container['conversionRate'];
    }

    /**
     * Sets conversionRate
     * @param float $conversionRate
     * @return $this
     */
    public function setConversionRate($conversionRate)
    {
        $this->container['conversionRate'] = $conversionRate;

        return $this;
    }

    /**
     * Gets conversions
     * @return int
     */
    public function getConversions()
    {
        return $this->container['conversions'];
    }

    /**
     * Sets conversions
     * @param int $conversions
     * @return $this
     */
    public function setConversions($conversions)
    {
        $this->container['conversions'] = $conversions;

        return $this;
    }

    /**
     * Gets date
     * @return string
     */
    public function getDate()
    {
        return $this->container['date'];
    }

    /**
     * Sets date
     * @param string $date
     * @return $this
     */
    public function setDate($date)
    {
        $this->container['date'] = $date;

        return $this;
    }

    /**
     * Gets fourteenDayAverage
     * @return float
     */
    public function getFourteenDayAverage()
    {
        return $this->container['fourteenDayAverage'];
    }

    /**
     * Sets fourteenDayAverage
     * @param float $fourteenDayAverage
     * @return $this
     */
    public function setFourteenDayAverage($fourteenDayAverage)
    {
        $this->container['fourteenDayAverage'] = $fourteenDayAverage;

        return $this;
    }

    /**
     * Gets payout
     * @return float
     */
    public function getPayout()
    {
        return $this->container['payout'];
    }

    /**
     * Sets payout
     * @param float $payout
     * @return $this
     */
    public function setPayout($payout)
    {
        $this->container['payout'] = $payout;

        return $this;
    }

    /**
     * Gets weekOverWeekAverage
     * @return float
     */
    public function getWeekOverWeekAverage()
    {
        return $this->container['weekOverWeekAverage'];
    }

    /**
     * Sets weekOverWeekAverage
     * @param float $weekOverWeekAverage
     * @return $this
     */
    public function setWeekOverWeekAverage($weekOverWeekAverage)
    {
        $this->container['weekOverWeekAverage'] = $weekOverWeekAverage;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}


