<?php
/**
 * RecurringOfferInterval
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * RevenueWire JackFruit REST API (Alpha)
 *
 * This API *does not* represent the final product. Some of the APIs listed below are *highly experimental* and *will likely change* before the final release. They may come with *crashes and bugs* and may potentially cause *data loss*.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;

/**
 * RecurringOfferInterval Class Doc Comment
 *
 * @category    Class
 * @description Recurring Offer Interval
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RecurringOfferInterval implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'RecurringOfferInterval';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'id' => 'int',
        'interval' => 'float',
        'offerId' => 'float',
        'affiliatePayout' => '\Swagger\Client\Model\AffiliatePayoutItem',
        'recurringOfferIntervalPrices' => '\Swagger\Client\Model\OfferPrices'
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'interval' => 'interval',
        'offerId' => 'offerId',
        'affiliatePayout' => 'affiliatePayout',
        'recurringOfferIntervalPrices' => 'recurringOfferIntervalPrices'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'interval' => 'setInterval',
        'offerId' => 'setOfferId',
        'affiliatePayout' => 'setAffiliatePayout',
        'recurringOfferIntervalPrices' => 'setRecurringOfferIntervalPrices'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'interval' => 'getInterval',
        'offerId' => 'getOfferId',
        'affiliatePayout' => 'getAffiliatePayout',
        'recurringOfferIntervalPrices' => 'getRecurringOfferIntervalPrices'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['interval'] = isset($data['interval']) ? $data['interval'] : null;
        $this->container['offerId'] = isset($data['offerId']) ? $data['offerId'] : null;
        $this->container['affiliatePayout'] = isset($data['affiliatePayout']) ? $data['affiliatePayout'] : null;
        $this->container['recurringOfferIntervalPrices'] = isset($data['recurringOfferIntervalPrices']) ? $data['recurringOfferIntervalPrices'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets id
     * @return int
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     * @param int $id Recurring Offer Interval Id
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets interval
     * @return float
     */
    public function getInterval()
    {
        return $this->container['interval'];
    }

    /**
     * Sets interval
     * @param float $interval Recurring Offer Interval
     * @return $this
     */
    public function setInterval($interval)
    {
        $this->container['interval'] = $interval;

        return $this;
    }

    /**
     * Gets offerId
     * @return float
     */
    public function getOfferId()
    {
        return $this->container['offerId'];
    }

    /**
     * Sets offerId
     * @param float $offerId Offer Id Linked to Interval
     * @return $this
     */
    public function setOfferId($offerId)
    {
        $this->container['offerId'] = $offerId;

        return $this;
    }

    /**
     * Gets affiliatePayout
     * @return \Swagger\Client\Model\AffiliatePayoutItem
     */
    public function getAffiliatePayout()
    {
        return $this->container['affiliatePayout'];
    }

    /**
     * Sets affiliatePayout
     * @param \Swagger\Client\Model\AffiliatePayoutItem $affiliatePayout
     * @return $this
     */
    public function setAffiliatePayout($affiliatePayout)
    {
        $this->container['affiliatePayout'] = $affiliatePayout;

        return $this;
    }

    /**
     * Gets recurringOfferIntervalPrices
     * @return \Swagger\Client\Model\OfferPrices
     */
    public function getRecurringOfferIntervalPrices()
    {
        return $this->container['recurringOfferIntervalPrices'];
    }

    /**
     * Sets recurringOfferIntervalPrices
     * @param \Swagger\Client\Model\OfferPrices $recurringOfferIntervalPrices
     * @return $this
     */
    public function setRecurringOfferIntervalPrices($recurringOfferIntervalPrices)
    {
        $this->container['recurringOfferIntervalPrices'] = $recurringOfferIntervalPrices;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}


