<?php
/**
 * RevshareSummaryData
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * RevenueWire JackFruit REST API (Alpha)
 *
 * This API *does not* represent the final product. Some of the APIs listed below are *highly experimental* and *will likely change* before the final release. They may come with *crashes and bugs* and may potentially cause *data loss*.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;

/**
 * RevshareSummaryData Class Doc Comment
 *
 * @category    Class
 * @description Revshare data object
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RevshareSummaryData implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'RevshareSummaryData';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'date' => 'string',
        'orders' => 'float',
        'sales' => 'float',
        'refunds' => 'float',
        'refundRate' => 'float',
        'chargebacks' => 'float',
        'chargebackRate' => 'float'
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'date' => 'date',
        'orders' => 'orders',
        'sales' => 'sales',
        'refunds' => 'refunds',
        'refundRate' => 'refundRate',
        'chargebacks' => 'chargebacks',
        'chargebackRate' => 'chargebackRate'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'date' => 'setDate',
        'orders' => 'setOrders',
        'sales' => 'setSales',
        'refunds' => 'setRefunds',
        'refundRate' => 'setRefundRate',
        'chargebacks' => 'setChargebacks',
        'chargebackRate' => 'setChargebackRate'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'date' => 'getDate',
        'orders' => 'getOrders',
        'sales' => 'getSales',
        'refunds' => 'getRefunds',
        'refundRate' => 'getRefundRate',
        'chargebacks' => 'getChargebacks',
        'chargebackRate' => 'getChargebackRate'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['date'] = isset($data['date']) ? $data['date'] : null;
        $this->container['orders'] = isset($data['orders']) ? $data['orders'] : null;
        $this->container['sales'] = isset($data['sales']) ? $data['sales'] : null;
        $this->container['refunds'] = isset($data['refunds']) ? $data['refunds'] : null;
        $this->container['refundRate'] = isset($data['refundRate']) ? $data['refundRate'] : null;
        $this->container['chargebacks'] = isset($data['chargebacks']) ? $data['chargebacks'] : null;
        $this->container['chargebackRate'] = isset($data['chargebackRate']) ? $data['chargebackRate'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        if ($this->container['date'] === null) {
            $invalid_properties[] = "'date' can't be null";
        }
        if ($this->container['orders'] === null) {
            $invalid_properties[] = "'orders' can't be null";
        }
        if ($this->container['sales'] === null) {
            $invalid_properties[] = "'sales' can't be null";
        }
        if ($this->container['refunds'] === null) {
            $invalid_properties[] = "'refunds' can't be null";
        }
        if ($this->container['refundRate'] === null) {
            $invalid_properties[] = "'refundRate' can't be null";
        }
        if ($this->container['chargebacks'] === null) {
            $invalid_properties[] = "'chargebacks' can't be null";
        }
        if ($this->container['chargebackRate'] === null) {
            $invalid_properties[] = "'chargebackRate' can't be null";
        }
        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        if ($this->container['date'] === null) {
            return false;
        }
        if ($this->container['orders'] === null) {
            return false;
        }
        if ($this->container['sales'] === null) {
            return false;
        }
        if ($this->container['refunds'] === null) {
            return false;
        }
        if ($this->container['refundRate'] === null) {
            return false;
        }
        if ($this->container['chargebacks'] === null) {
            return false;
        }
        if ($this->container['chargebackRate'] === null) {
            return false;
        }
        return true;
    }


    /**
     * Gets date
     * @return string
     */
    public function getDate()
    {
        return $this->container['date'];
    }

    /**
     * Sets date
     * @param string $date
     * @return $this
     */
    public function setDate($date)
    {
        $this->container['date'] = $date;

        return $this;
    }

    /**
     * Gets orders
     * @return float
     */
    public function getOrders()
    {
        return $this->container['orders'];
    }

    /**
     * Sets orders
     * @param float $orders
     * @return $this
     */
    public function setOrders($orders)
    {
        $this->container['orders'] = $orders;

        return $this;
    }

    /**
     * Gets sales
     * @return float
     */
    public function getSales()
    {
        return $this->container['sales'];
    }

    /**
     * Sets sales
     * @param float $sales
     * @return $this
     */
    public function setSales($sales)
    {
        $this->container['sales'] = $sales;

        return $this;
    }

    /**
     * Gets refunds
     * @return float
     */
    public function getRefunds()
    {
        return $this->container['refunds'];
    }

    /**
     * Sets refunds
     * @param float $refunds
     * @return $this
     */
    public function setRefunds($refunds)
    {
        $this->container['refunds'] = $refunds;

        return $this;
    }

    /**
     * Gets refundRate
     * @return float
     */
    public function getRefundRate()
    {
        return $this->container['refundRate'];
    }

    /**
     * Sets refundRate
     * @param float $refundRate
     * @return $this
     */
    public function setRefundRate($refundRate)
    {
        $this->container['refundRate'] = $refundRate;

        return $this;
    }

    /**
     * Gets chargebacks
     * @return float
     */
    public function getChargebacks()
    {
        return $this->container['chargebacks'];
    }

    /**
     * Sets chargebacks
     * @param float $chargebacks
     * @return $this
     */
    public function setChargebacks($chargebacks)
    {
        $this->container['chargebacks'] = $chargebacks;

        return $this;
    }

    /**
     * Gets chargebackRate
     * @return float
     */
    public function getChargebackRate()
    {
        return $this->container['chargebackRate'];
    }

    /**
     * Sets chargebackRate
     * @param float $chargebackRate
     * @return $this
     */
    public function setChargebackRate($chargebackRate)
    {
        $this->container['chargebackRate'] = $chargebackRate;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}


