<?php
/**
 * AffiliateAccountTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * RevenueWire JackFruit REST API (Alpha)
 *
 * This API *does not* represent the final product. Some of the APIs listed below are *highly experimental* and *will likely change* before the final release. They may come with *crashes and bugs* and may potentially cause *data loss*.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * AffiliateAccountTest Class Doc Comment
 *
 * @category    Class */
// * @description Affiliate Account object
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AffiliateAccountTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "AffiliateAccount"
     */
    public function testAffiliateAccount()
    {

    }

    /**
     * Test attribute "accountFid"
     */
    public function testPropertyAccountFid()
    {

    }

    /**
     * Test attribute "apiKey"
     */
    public function testPropertyApiKey()
    {

    }

    /**
     * Test attribute "companyName"
     */
    public function testPropertyCompanyName()
    {

    }

    /**
     * Test attribute "website"
     */
    public function testPropertyWebsite()
    {

    }

    /**
     * Test attribute "phone"
     */
    public function testPropertyPhone()
    {

    }

    /**
     * Test attribute "contactName"
     */
    public function testPropertyContactName()
    {

    }

    /**
     * Test attribute "technicalEmail"
     */
    public function testPropertyTechnicalEmail()
    {

    }

    /**
     * Test attribute "address"
     */
    public function testPropertyAddress()
    {

    }

    /**
     * Test attribute "city"
     */
    public function testPropertyCity()
    {

    }

    /**
     * Test attribute "stateProvince"
     */
    public function testPropertyStateProvince()
    {

    }

    /**
     * Test attribute "zipPostalCode"
     */
    public function testPropertyZipPostalCode()
    {

    }

    /**
     * Test attribute "gstNumber"
     */
    public function testPropertyGstNumber()
    {

    }

    /**
     * Test attribute "taxRegion"
     */
    public function testPropertyTaxRegion()
    {

    }

    /**
     * Test attribute "paymentThreshold"
     */
    public function testPropertyPaymentThreshold()
    {

    }

}
