<?php
/**
 * OfferTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * JackFruit REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * OfferTest Class Doc Comment
 *
 * @category    Class */
// * @description Offer
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OfferTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "Offer"
     */
    public function testOffer()
    {

    }

    /**
     * Test attribute "offer_id"
     */
    public function testPropertyOfferId()
    {

    }

    /**
     * Test attribute "transaction_item_id"
     */
    public function testPropertyTransactionItemId()
    {

    }

    /**
     * Test attribute "transaction_id"
     */
    public function testPropertyTransactionId()
    {

    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {

    }

    /**
     * Test attribute "translated_name"
     */
    public function testPropertyTranslatedName()
    {

    }

    /**
     * Test attribute "product_name"
     */
    public function testPropertyProductName()
    {

    }

    /**
     * Test attribute "translated_product_name"
     */
    public function testPropertyTranslatedProductName()
    {

    }

    /**
     * Test attribute "is_recurring"
     */
    public function testPropertyIsRecurring()
    {

    }

    /**
     * Test attribute "is_trial"
     */
    public function testPropertyIsTrial()
    {

    }

    /**
     * Test attribute "transaction_item"
     */
    public function testPropertyTransactionItem()
    {

    }

    /**
     * Test attribute "recurring_item"
     */
    public function testPropertyRecurringItem()
    {

    }

}
