<?php
/**
 * OrderDetailedObjTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * RevenueWire JackFruit REST API (Alpha)
 *
 * This API *does not* represent the final product. Some of the APIs listed below are *highly experimental* and *will likely change* before the final release. They may come with *crashes and bugs* and may potentially cause *data loss*.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * OrderDetailedObjTest Class Doc Comment
 *
 * @category    Class */
// * @description Details of an order
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OrderDetailedObjTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "OrderDetailedObj"
     */
    public function testOrderDetailedObj()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "orderReference"
     */
    public function testPropertyOrderReference()
    {

    }

    /**
     * Test attribute "created"
     */
    public function testPropertyCreated()
    {

    }

    /**
     * Test attribute "hostId"
     */
    public function testPropertyHostId()
    {

    }

    /**
     * Test attribute "customerGroupAccountId"
     */
    public function testPropertyCustomerGroupAccountId()
    {

    }

    /**
     * Test attribute "merchantGroupAccountId"
     */
    public function testPropertyMerchantGroupAccountId()
    {

    }

    /**
     * Test attribute "affiliateGroupAccountId"
     */
    public function testPropertyAffiliateGroupAccountId()
    {

    }

    /**
     * Test attribute "currencyCode"
     */
    public function testPropertyCurrencyCode()
    {

    }

    /**
     * Test attribute "language"
     */
    public function testPropertyLanguage()
    {

    }

    /**
     * Test attribute "countryCode"
     */
    public function testPropertyCountryCode()
    {

    }

    /**
     * Test attribute "regionCode"
     */
    public function testPropertyRegionCode()
    {

    }

}
