<?php
/**
 * ProfileTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * JackFruit REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ProfileTest Class Doc Comment
 *
 * @category    Class */
// * @description User&#39;s Profile
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ProfileTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "Profile"
     */
    public function testProfile()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "username"
     */
    public function testPropertyUsername()
    {

    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {

    }

    /**
     * Test attribute "first_name"
     */
    public function testPropertyFirstName()
    {

    }

    /**
     * Test attribute "last_name"
     */
    public function testPropertyLastName()
    {

    }

    /**
     * Test attribute "timezone"
     */
    public function testPropertyTimezone()
    {

    }

    /**
     * Test attribute "account_id"
     */
    public function testPropertyAccountId()
    {

    }

    /**
     * Test attribute "password_expiry_dates"
     */
    public function testPropertyPasswordExpiryDates()
    {

    }

    /**
     * Test attribute "default_dashboard"
     */
    public function testPropertyDefaultDashboard()
    {

    }

    /**
     * Test attribute "default_product_view"
     */
    public function testPropertyDefaultProductView()
    {

    }

    /**
     * Test attribute "last_login_date"
     */
    public function testPropertyLastLoginDate()
    {

    }

    /**
     * Test attribute "last_login_ip"
     */
    public function testPropertyLastLoginIp()
    {

    }

}
