<?php
/**
 * ReportsPerformanceApi
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * RevenueWire JackFruit REST API (Alpha)
 *
 * This API *does not* represent the final product. Some of the APIs listed below are *highly experimental* and *will likely change* before the final release. They may come with *crashes and bugs* and may potentially cause *data loss*.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Jackfruit;

use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\Configuration;
use \Swagger\Client\ObjectSerializer;

/**
 * ReportsPerformanceApi Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ReportsPerformanceApi
{
    /**
     * API Client
     *
     * @var \Swagger\Client\ApiClient instance of the ApiClient
     */
    protected $apiClient;

    /**
     * Constructor
     *
     * @param \Swagger\Client\ApiClient|null $apiClient The api client to use
     */
    public function __construct(\Swagger\Client\ApiClient $apiClient = null)
    {
        if ($apiClient === null) {
            $apiClient = new ApiClient();
        }

        $this->apiClient = $apiClient;
    }

    /**
     * Get API client
     *
     * @return \Swagger\Client\ApiClient get the API client
     */
    public function getApiClient()
    {
        return $this->apiClient;
    }

    /**
     * Set the API client
     *
     * @param \Swagger\Client\ApiClient $apiClient set the API client
     *
     * @return ReportsPerformanceApi
     */
    public function setApiClient(\Swagger\Client\ApiClient $apiClient)
    {
        $this->apiClient = $apiClient;
        return $this;
    }

    /**
     * Operation reportsPerformance
     *
     * 
     *
     * @param string $start Start date (YYYY-MM-DD) (required)
     * @param string $end End date (YYYY-MM-DD) (required)
     * @param string[] $offerTypes A JSON encoded array of offer types (eg [\&quot;download\&quot;,\&quot;lead\&quot;]) (required)
     * @param string[] $categories A JSON encoded array of offer categories (eg [\&quot;antimalware\&quot;,\&quot;drivers\&quot;]) (required)
     * @param string[] $aliases A JSON encoded array of alias IDs (eg [\&quot;1\&quot;,\&quot;2\&quot;]) (required)
     * @param string $graphScale The x-axis scale to use for graph data. Also defines the length of &#39;period&#39; when grouping on &#39;period&#39;. (required)
     * @param string[] $graphMetric The y-axis metrics to use for graph data. A JSON encoded array of one or two strings (eg. [\&quot;col1\&quot;,\&quot;col2\&quot;]) (required)
     * @param \Swagger\Client\Model\Sort1 $sort A JSON encoded object with the column to sort on and the sort direction (eg. {\&quot;col\&quot;:\&quot;sales\&quot;,\&quot;dir\&quot;:\&quot;DESC\&quot;}) (required)
     * @param string[] $groupableColumns A JSON encoded array with the columns to group data on (eg. [\&quot;period\&quot;,\&quot;alias\&quot;]) (required)
     * @param \Swagger\Client\Model\Pagination $pagination A JSON encoded array with the columns to group data on (eg. [\&quot;period\&quot;,\&quot;alias\&quot;]) (required)
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @return \Swagger\Client\Model\SafecartCampaignDatas
     */
    public function reportsPerformance($start, $end, $offerTypes, $categories, $aliases, $graphScale, $graphMetric, $sort, $groupableColumns, $pagination)
    {
        list($response) = $this->reportsPerformanceWithHttpInfo($start, $end, $offerTypes, $categories, $aliases, $graphScale, $graphMetric, $sort, $groupableColumns, $pagination);
        return $response;
    }

    /**
     * Operation reportsPerformanceWithHttpInfo
     *
     * 
     *
     * @param string $start Start date (YYYY-MM-DD) (required)
     * @param string $end End date (YYYY-MM-DD) (required)
     * @param string[] $offerTypes A JSON encoded array of offer types (eg [\&quot;download\&quot;,\&quot;lead\&quot;]) (required)
     * @param string[] $categories A JSON encoded array of offer categories (eg [\&quot;antimalware\&quot;,\&quot;drivers\&quot;]) (required)
     * @param string[] $aliases A JSON encoded array of alias IDs (eg [\&quot;1\&quot;,\&quot;2\&quot;]) (required)
     * @param string $graphScale The x-axis scale to use for graph data. Also defines the length of &#39;period&#39; when grouping on &#39;period&#39;. (required)
     * @param string[] $graphMetric The y-axis metrics to use for graph data. A JSON encoded array of one or two strings (eg. [\&quot;col1\&quot;,\&quot;col2\&quot;]) (required)
     * @param \Swagger\Client\Model\Sort1 $sort A JSON encoded object with the column to sort on and the sort direction (eg. {\&quot;col\&quot;:\&quot;sales\&quot;,\&quot;dir\&quot;:\&quot;DESC\&quot;}) (required)
     * @param string[] $groupableColumns A JSON encoded array with the columns to group data on (eg. [\&quot;period\&quot;,\&quot;alias\&quot;]) (required)
     * @param \Swagger\Client\Model\Pagination $pagination A JSON encoded array with the columns to group data on (eg. [\&quot;period\&quot;,\&quot;alias\&quot;]) (required)
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @return array of \Swagger\Client\Model\SafecartCampaignDatas, HTTP status code, HTTP response headers (array of strings)
     */
    public function reportsPerformanceWithHttpInfo($start, $end, $offerTypes, $categories, $aliases, $graphScale, $graphMetric, $sort, $groupableColumns, $pagination)
    {
        // verify the required parameter 'start' is set
        if ($start === null) {
            throw new \InvalidArgumentException('Missing the required parameter $start when calling reportsPerformance');
        }
        // verify the required parameter 'end' is set
        if ($end === null) {
            throw new \InvalidArgumentException('Missing the required parameter $end when calling reportsPerformance');
        }
        // verify the required parameter 'offerTypes' is set
        if ($offerTypes === null) {
            throw new \InvalidArgumentException('Missing the required parameter $offerTypes when calling reportsPerformance');
        }
        // verify the required parameter 'categories' is set
        if ($categories === null) {
            throw new \InvalidArgumentException('Missing the required parameter $categories when calling reportsPerformance');
        }
        // verify the required parameter 'aliases' is set
        if ($aliases === null) {
            throw new \InvalidArgumentException('Missing the required parameter $aliases when calling reportsPerformance');
        }
        // verify the required parameter 'graphScale' is set
        if ($graphScale === null) {
            throw new \InvalidArgumentException('Missing the required parameter $graphScale when calling reportsPerformance');
        }
        // verify the required parameter 'graphMetric' is set
        if ($graphMetric === null) {
            throw new \InvalidArgumentException('Missing the required parameter $graphMetric when calling reportsPerformance');
        }
        // verify the required parameter 'sort' is set
        if ($sort === null) {
            throw new \InvalidArgumentException('Missing the required parameter $sort when calling reportsPerformance');
        }
        // verify the required parameter 'groupableColumns' is set
        if ($groupableColumns === null) {
            throw new \InvalidArgumentException('Missing the required parameter $groupableColumns when calling reportsPerformance');
        }
        // verify the required parameter 'pagination' is set
        if ($pagination === null) {
            throw new \InvalidArgumentException('Missing the required parameter $pagination when calling reportsPerformance');
        }
        // parse inputs
        $resourcePath = "/reports/safecartcampaign";
        $httpBody = '';
        $queryParams = [];
        $headerParams = [];
        $formParams = [];
        $_header_accept = $this->apiClient->selectHeaderAccept(['application/json']);
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(['application/json']);

        // query params
        if ($start !== null) {
            $queryParams['start'] = $this->apiClient->getSerializer()->toQueryValue($start);
        }
        // query params
        if ($end !== null) {
            $queryParams['end'] = $this->apiClient->getSerializer()->toQueryValue($end);
        }
        // query params
        if (is_array($offerTypes)) {
            $offerTypes = $this->apiClient->getSerializer()->serializeCollection($offerTypes, 'csv', true);
        }
        if ($offerTypes !== null) {
            $queryParams['offerTypes'] = $this->apiClient->getSerializer()->toQueryValue($offerTypes);
        }
        // query params
        if (is_array($categories)) {
            $categories = $this->apiClient->getSerializer()->serializeCollection($categories, 'csv', true);
        }
        if ($categories !== null) {
            $queryParams['categories'] = $this->apiClient->getSerializer()->toQueryValue($categories);
        }
        // query params
        if (is_array($aliases)) {
            $aliases = $this->apiClient->getSerializer()->serializeCollection($aliases, 'csv', true);
        }
        if ($aliases !== null) {
            $queryParams['aliases'] = $this->apiClient->getSerializer()->toQueryValue($aliases);
        }
        // query params
        if ($graphScale !== null) {
            $queryParams['graphScale'] = $this->apiClient->getSerializer()->toQueryValue($graphScale);
        }
        // query params
        if (is_array($graphMetric)) {
            $graphMetric = $this->apiClient->getSerializer()->serializeCollection($graphMetric, 'csv', true);
        }
        if ($graphMetric !== null) {
            $queryParams['graphMetric'] = $this->apiClient->getSerializer()->toQueryValue($graphMetric);
        }
        // query params
        if (is_array($groupableColumns)) {
            $groupableColumns = $this->apiClient->getSerializer()->serializeCollection($groupableColumns, 'csv', true);
        }
        if ($groupableColumns !== null) {
            $queryParams['groupableColumns'] = $this->apiClient->getSerializer()->toQueryValue($groupableColumns);
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        // body params
        $_tempBody = null;
        if (isset($sort)) {
            $_tempBody = $sort;
        }
// body params
        $_tempBody = null;
        if (isset($pagination)) {
            $_tempBody = $pagination;
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // this endpoint requires API key authentication
        $apiKey = $this->apiClient->getApiKeyWithPrefix('X-Authorization-JWT');
        if (strlen($apiKey) !== 0) {
            $headerParams['X-Authorization-JWT'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->apiClient->getApiKeyWithPrefix('X-API-KEY');
        if (strlen($apiKey) !== 0) {
            $headerParams['X-API-KEY'] = $apiKey;
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'GET',
                $queryParams,
                $httpBody,
                $headerParams,
                '\Swagger\Client\Model\SafecartCampaignDatas',
                '/reports/safecartcampaign'
            );

            return [$this->apiClient->getSerializer()->deserialize($response, '\Swagger\Client\Model\SafecartCampaignDatas', $httpHeader), $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Swagger\Client\Model\SafecartCampaignDatas', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Swagger\Client\Model\Error', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }

    /**
     * Operation reportsPerformanceCount
     *
     * 
     *
     * @param string $start Start date (YYYY-MM-DD) (required)
     * @param string $end End date (YYYY-MM-DD) (required)
     * @param string[] $offerTypes A JSON encoded array of offer types (eg [\&quot;download\&quot;,\&quot;lead\&quot;]) (required)
     * @param string[] $categories A JSON encoded array of offer categories (eg [\&quot;antimalware\&quot;,\&quot;drivers\&quot;]) (required)
     * @param string[] $aliases A JSON encoded array of alias IDs (eg [\&quot;1\&quot;,\&quot;2\&quot;]) (required)
     * @param string $graphScale The x-axis scale to use for graph data. Also defines the length of &#39;period&#39; when grouping on &#39;period&#39;. (required)
     * @param string[] $graphMetric The y-axis metrics to use for graph data. A JSON encoded array of one or two strings (eg. [\&quot;col1\&quot;,\&quot;col2\&quot;]) (required)
     * @param \Swagger\Client\Model\Sort1 $sort A JSON encoded object with the column to sort on and the sort direction (eg. {\&quot;col\&quot;:\&quot;sales\&quot;,\&quot;dir\&quot;:\&quot;DESC\&quot;}) (required)
     * @param string[] $groupableColumns A JSON encoded array with the columns to group data on (eg. [\&quot;period\&quot;,\&quot;alias\&quot;]) (required)
     * @param \Swagger\Client\Model\Pagination $pagination A JSON encoded array with the columns to group data on (eg. [\&quot;period\&quot;,\&quot;alias\&quot;]) (required)
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @return \Swagger\Client\Model\SafecartCampaignCountData
     */
    public function reportsPerformanceCount($start, $end, $offerTypes, $categories, $aliases, $graphScale, $graphMetric, $sort, $groupableColumns, $pagination)
    {
        list($response) = $this->reportsPerformanceCountWithHttpInfo($start, $end, $offerTypes, $categories, $aliases, $graphScale, $graphMetric, $sort, $groupableColumns, $pagination);
        return $response;
    }

    /**
     * Operation reportsPerformanceCountWithHttpInfo
     *
     * 
     *
     * @param string $start Start date (YYYY-MM-DD) (required)
     * @param string $end End date (YYYY-MM-DD) (required)
     * @param string[] $offerTypes A JSON encoded array of offer types (eg [\&quot;download\&quot;,\&quot;lead\&quot;]) (required)
     * @param string[] $categories A JSON encoded array of offer categories (eg [\&quot;antimalware\&quot;,\&quot;drivers\&quot;]) (required)
     * @param string[] $aliases A JSON encoded array of alias IDs (eg [\&quot;1\&quot;,\&quot;2\&quot;]) (required)
     * @param string $graphScale The x-axis scale to use for graph data. Also defines the length of &#39;period&#39; when grouping on &#39;period&#39;. (required)
     * @param string[] $graphMetric The y-axis metrics to use for graph data. A JSON encoded array of one or two strings (eg. [\&quot;col1\&quot;,\&quot;col2\&quot;]) (required)
     * @param \Swagger\Client\Model\Sort1 $sort A JSON encoded object with the column to sort on and the sort direction (eg. {\&quot;col\&quot;:\&quot;sales\&quot;,\&quot;dir\&quot;:\&quot;DESC\&quot;}) (required)
     * @param string[] $groupableColumns A JSON encoded array with the columns to group data on (eg. [\&quot;period\&quot;,\&quot;alias\&quot;]) (required)
     * @param \Swagger\Client\Model\Pagination $pagination A JSON encoded array with the columns to group data on (eg. [\&quot;period\&quot;,\&quot;alias\&quot;]) (required)
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @return array of \Swagger\Client\Model\SafecartCampaignCountData, HTTP status code, HTTP response headers (array of strings)
     */
    public function reportsPerformanceCountWithHttpInfo($start, $end, $offerTypes, $categories, $aliases, $graphScale, $graphMetric, $sort, $groupableColumns, $pagination)
    {
        // verify the required parameter 'start' is set
        if ($start === null) {
            throw new \InvalidArgumentException('Missing the required parameter $start when calling reportsPerformanceCount');
        }
        // verify the required parameter 'end' is set
        if ($end === null) {
            throw new \InvalidArgumentException('Missing the required parameter $end when calling reportsPerformanceCount');
        }
        // verify the required parameter 'offerTypes' is set
        if ($offerTypes === null) {
            throw new \InvalidArgumentException('Missing the required parameter $offerTypes when calling reportsPerformanceCount');
        }
        // verify the required parameter 'categories' is set
        if ($categories === null) {
            throw new \InvalidArgumentException('Missing the required parameter $categories when calling reportsPerformanceCount');
        }
        // verify the required parameter 'aliases' is set
        if ($aliases === null) {
            throw new \InvalidArgumentException('Missing the required parameter $aliases when calling reportsPerformanceCount');
        }
        // verify the required parameter 'graphScale' is set
        if ($graphScale === null) {
            throw new \InvalidArgumentException('Missing the required parameter $graphScale when calling reportsPerformanceCount');
        }
        // verify the required parameter 'graphMetric' is set
        if ($graphMetric === null) {
            throw new \InvalidArgumentException('Missing the required parameter $graphMetric when calling reportsPerformanceCount');
        }
        // verify the required parameter 'sort' is set
        if ($sort === null) {
            throw new \InvalidArgumentException('Missing the required parameter $sort when calling reportsPerformanceCount');
        }
        // verify the required parameter 'groupableColumns' is set
        if ($groupableColumns === null) {
            throw new \InvalidArgumentException('Missing the required parameter $groupableColumns when calling reportsPerformanceCount');
        }
        // verify the required parameter 'pagination' is set
        if ($pagination === null) {
            throw new \InvalidArgumentException('Missing the required parameter $pagination when calling reportsPerformanceCount');
        }
        // parse inputs
        $resourcePath = "/reports/safecartcampaign/count";
        $httpBody = '';
        $queryParams = [];
        $headerParams = [];
        $formParams = [];
        $_header_accept = $this->apiClient->selectHeaderAccept(['application/json']);
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(['application/json']);

        // query params
        if ($start !== null) {
            $queryParams['start'] = $this->apiClient->getSerializer()->toQueryValue($start);
        }
        // query params
        if ($end !== null) {
            $queryParams['end'] = $this->apiClient->getSerializer()->toQueryValue($end);
        }
        // query params
        if (is_array($offerTypes)) {
            $offerTypes = $this->apiClient->getSerializer()->serializeCollection($offerTypes, 'csv', true);
        }
        if ($offerTypes !== null) {
            $queryParams['offerTypes'] = $this->apiClient->getSerializer()->toQueryValue($offerTypes);
        }
        // query params
        if (is_array($categories)) {
            $categories = $this->apiClient->getSerializer()->serializeCollection($categories, 'csv', true);
        }
        if ($categories !== null) {
            $queryParams['categories'] = $this->apiClient->getSerializer()->toQueryValue($categories);
        }
        // query params
        if (is_array($aliases)) {
            $aliases = $this->apiClient->getSerializer()->serializeCollection($aliases, 'csv', true);
        }
        if ($aliases !== null) {
            $queryParams['aliases'] = $this->apiClient->getSerializer()->toQueryValue($aliases);
        }
        // query params
        if ($graphScale !== null) {
            $queryParams['graphScale'] = $this->apiClient->getSerializer()->toQueryValue($graphScale);
        }
        // query params
        if (is_array($graphMetric)) {
            $graphMetric = $this->apiClient->getSerializer()->serializeCollection($graphMetric, 'csv', true);
        }
        if ($graphMetric !== null) {
            $queryParams['graphMetric'] = $this->apiClient->getSerializer()->toQueryValue($graphMetric);
        }
        // query params
        if (is_array($groupableColumns)) {
            $groupableColumns = $this->apiClient->getSerializer()->serializeCollection($groupableColumns, 'csv', true);
        }
        if ($groupableColumns !== null) {
            $queryParams['groupableColumns'] = $this->apiClient->getSerializer()->toQueryValue($groupableColumns);
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        // body params
        $_tempBody = null;
        if (isset($sort)) {
            $_tempBody = $sort;
        }
// body params
        $_tempBody = null;
        if (isset($pagination)) {
            $_tempBody = $pagination;
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // this endpoint requires API key authentication
        $apiKey = $this->apiClient->getApiKeyWithPrefix('X-Authorization-JWT');
        if (strlen($apiKey) !== 0) {
            $headerParams['X-Authorization-JWT'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->apiClient->getApiKeyWithPrefix('X-API-KEY');
        if (strlen($apiKey) !== 0) {
            $headerParams['X-API-KEY'] = $apiKey;
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'GET',
                $queryParams,
                $httpBody,
                $headerParams,
                '\Swagger\Client\Model\SafecartCampaignCountData',
                '/reports/safecartcampaign/count'
            );

            return [$this->apiClient->getSerializer()->deserialize($response, '\Swagger\Client\Model\SafecartCampaignCountData', $httpHeader), $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Swagger\Client\Model\SafecartCampaignCountData', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Swagger\Client\Model\Error', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }

    /**
     * Operation reportsPerformanceExport
     *
     * 
     *
     * @param string $start Start date (YYYY-MM-DD) (required)
     * @param string $end End date (YYYY-MM-DD) (required)
     * @param string[] $offerTypes A JSON encoded array of offer types (eg [\&quot;download\&quot;,\&quot;lead\&quot;]) (required)
     * @param string[] $categories A JSON encoded array of offer categories (eg [\&quot;antimalware\&quot;,\&quot;drivers\&quot;]) (required)
     * @param string[] $aliases A JSON encoded array of alias IDs (eg [\&quot;1\&quot;,\&quot;2\&quot;]) (required)
     * @param string $graphScale The x-axis scale to use for graph data. Also defines the length of &#39;period&#39; when grouping on &#39;period&#39;. (required)
     * @param string[] $graphMetric The y-axis metrics to use for graph data. A JSON encoded array of one or two strings (eg. [\&quot;col1\&quot;,\&quot;col2\&quot;]) (required)
     * @param \Swagger\Client\Model\Sort1 $sort A JSON encoded object with the column to sort on and the sort direction (eg. {\&quot;col\&quot;:\&quot;sales\&quot;,\&quot;dir\&quot;:\&quot;DESC\&quot;}) (required)
     * @param string[] $groupableColumns A JSON encoded array with the columns to group data on (eg. [\&quot;period\&quot;,\&quot;alias\&quot;]) (required)
     * @param \Swagger\Client\Model\Pagination $pagination A JSON encoded array with the columns to group data on (eg. [\&quot;period\&quot;,\&quot;alias\&quot;]) (required)
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @return \Swagger\Client\Model\SafecartCampaignExportData
     */
    public function reportsPerformanceExport($start, $end, $offerTypes, $categories, $aliases, $graphScale, $graphMetric, $sort, $groupableColumns, $pagination)
    {
        list($response) = $this->reportsPerformanceExportWithHttpInfo($start, $end, $offerTypes, $categories, $aliases, $graphScale, $graphMetric, $sort, $groupableColumns, $pagination);
        return $response;
    }

    /**
     * Operation reportsPerformanceExportWithHttpInfo
     *
     * 
     *
     * @param string $start Start date (YYYY-MM-DD) (required)
     * @param string $end End date (YYYY-MM-DD) (required)
     * @param string[] $offerTypes A JSON encoded array of offer types (eg [\&quot;download\&quot;,\&quot;lead\&quot;]) (required)
     * @param string[] $categories A JSON encoded array of offer categories (eg [\&quot;antimalware\&quot;,\&quot;drivers\&quot;]) (required)
     * @param string[] $aliases A JSON encoded array of alias IDs (eg [\&quot;1\&quot;,\&quot;2\&quot;]) (required)
     * @param string $graphScale The x-axis scale to use for graph data. Also defines the length of &#39;period&#39; when grouping on &#39;period&#39;. (required)
     * @param string[] $graphMetric The y-axis metrics to use for graph data. A JSON encoded array of one or two strings (eg. [\&quot;col1\&quot;,\&quot;col2\&quot;]) (required)
     * @param \Swagger\Client\Model\Sort1 $sort A JSON encoded object with the column to sort on and the sort direction (eg. {\&quot;col\&quot;:\&quot;sales\&quot;,\&quot;dir\&quot;:\&quot;DESC\&quot;}) (required)
     * @param string[] $groupableColumns A JSON encoded array with the columns to group data on (eg. [\&quot;period\&quot;,\&quot;alias\&quot;]) (required)
     * @param \Swagger\Client\Model\Pagination $pagination A JSON encoded array with the columns to group data on (eg. [\&quot;period\&quot;,\&quot;alias\&quot;]) (required)
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @return array of \Swagger\Client\Model\SafecartCampaignExportData, HTTP status code, HTTP response headers (array of strings)
     */
    public function reportsPerformanceExportWithHttpInfo($start, $end, $offerTypes, $categories, $aliases, $graphScale, $graphMetric, $sort, $groupableColumns, $pagination)
    {
        // verify the required parameter 'start' is set
        if ($start === null) {
            throw new \InvalidArgumentException('Missing the required parameter $start when calling reportsPerformanceExport');
        }
        // verify the required parameter 'end' is set
        if ($end === null) {
            throw new \InvalidArgumentException('Missing the required parameter $end when calling reportsPerformanceExport');
        }
        // verify the required parameter 'offerTypes' is set
        if ($offerTypes === null) {
            throw new \InvalidArgumentException('Missing the required parameter $offerTypes when calling reportsPerformanceExport');
        }
        // verify the required parameter 'categories' is set
        if ($categories === null) {
            throw new \InvalidArgumentException('Missing the required parameter $categories when calling reportsPerformanceExport');
        }
        // verify the required parameter 'aliases' is set
        if ($aliases === null) {
            throw new \InvalidArgumentException('Missing the required parameter $aliases when calling reportsPerformanceExport');
        }
        // verify the required parameter 'graphScale' is set
        if ($graphScale === null) {
            throw new \InvalidArgumentException('Missing the required parameter $graphScale when calling reportsPerformanceExport');
        }
        // verify the required parameter 'graphMetric' is set
        if ($graphMetric === null) {
            throw new \InvalidArgumentException('Missing the required parameter $graphMetric when calling reportsPerformanceExport');
        }
        // verify the required parameter 'sort' is set
        if ($sort === null) {
            throw new \InvalidArgumentException('Missing the required parameter $sort when calling reportsPerformanceExport');
        }
        // verify the required parameter 'groupableColumns' is set
        if ($groupableColumns === null) {
            throw new \InvalidArgumentException('Missing the required parameter $groupableColumns when calling reportsPerformanceExport');
        }
        // verify the required parameter 'pagination' is set
        if ($pagination === null) {
            throw new \InvalidArgumentException('Missing the required parameter $pagination when calling reportsPerformanceExport');
        }
        // parse inputs
        $resourcePath = "/reports/safecartcampaign/export";
        $httpBody = '';
        $queryParams = [];
        $headerParams = [];
        $formParams = [];
        $_header_accept = $this->apiClient->selectHeaderAccept(['application/json']);
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(['application/json']);

        // query params
        if ($start !== null) {
            $queryParams['start'] = $this->apiClient->getSerializer()->toQueryValue($start);
        }
        // query params
        if ($end !== null) {
            $queryParams['end'] = $this->apiClient->getSerializer()->toQueryValue($end);
        }
        // query params
        if (is_array($offerTypes)) {
            $offerTypes = $this->apiClient->getSerializer()->serializeCollection($offerTypes, 'csv', true);
        }
        if ($offerTypes !== null) {
            $queryParams['offerTypes'] = $this->apiClient->getSerializer()->toQueryValue($offerTypes);
        }
        // query params
        if (is_array($categories)) {
            $categories = $this->apiClient->getSerializer()->serializeCollection($categories, 'csv', true);
        }
        if ($categories !== null) {
            $queryParams['categories'] = $this->apiClient->getSerializer()->toQueryValue($categories);
        }
        // query params
        if (is_array($aliases)) {
            $aliases = $this->apiClient->getSerializer()->serializeCollection($aliases, 'csv', true);
        }
        if ($aliases !== null) {
            $queryParams['aliases'] = $this->apiClient->getSerializer()->toQueryValue($aliases);
        }
        // query params
        if ($graphScale !== null) {
            $queryParams['graphScale'] = $this->apiClient->getSerializer()->toQueryValue($graphScale);
        }
        // query params
        if (is_array($graphMetric)) {
            $graphMetric = $this->apiClient->getSerializer()->serializeCollection($graphMetric, 'csv', true);
        }
        if ($graphMetric !== null) {
            $queryParams['graphMetric'] = $this->apiClient->getSerializer()->toQueryValue($graphMetric);
        }
        // query params
        if (is_array($groupableColumns)) {
            $groupableColumns = $this->apiClient->getSerializer()->serializeCollection($groupableColumns, 'csv', true);
        }
        if ($groupableColumns !== null) {
            $queryParams['groupableColumns'] = $this->apiClient->getSerializer()->toQueryValue($groupableColumns);
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        // body params
        $_tempBody = null;
        if (isset($sort)) {
            $_tempBody = $sort;
        }
// body params
        $_tempBody = null;
        if (isset($pagination)) {
            $_tempBody = $pagination;
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // this endpoint requires API key authentication
        $apiKey = $this->apiClient->getApiKeyWithPrefix('X-Authorization-JWT');
        if (strlen($apiKey) !== 0) {
            $headerParams['X-Authorization-JWT'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->apiClient->getApiKeyWithPrefix('X-API-KEY');
        if (strlen($apiKey) !== 0) {
            $headerParams['X-API-KEY'] = $apiKey;
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'GET',
                $queryParams,
                $httpBody,
                $headerParams,
                '\Swagger\Client\Model\SafecartCampaignExportData',
                '/reports/safecartcampaign/export'
            );

            return [$this->apiClient->getSerializer()->deserialize($response, '\Swagger\Client\Model\SafecartCampaignExportData', $httpHeader), $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Swagger\Client\Model\SafecartCampaignExportData', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Swagger\Client\Model\Error', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }

    /**
     * Operation reportsPerformanceGraph
     *
     * 
     *
     * @param string $start Start date (YYYY-MM-DD) (required)
     * @param string $end End date (YYYY-MM-DD) (required)
     * @param string[] $offerTypes A JSON encoded array of offer types (eg [\&quot;download\&quot;,\&quot;lead\&quot;]) (required)
     * @param string[] $categories A JSON encoded array of offer categories (eg [\&quot;antimalware\&quot;,\&quot;drivers\&quot;]) (required)
     * @param string[] $aliases A JSON encoded array of alias IDs (eg [\&quot;1\&quot;,\&quot;2\&quot;]) (required)
     * @param string $graphScale The x-axis scale to use for graph data. Also defines the length of &#39;period&#39; when grouping on &#39;period&#39;. (required)
     * @param string[] $graphMetric The y-axis metrics to use for graph data. A JSON encoded array of one or two strings (eg. [\&quot;col1\&quot;,\&quot;col2\&quot;]) (required)
     * @param \Swagger\Client\Model\Sort1 $sort A JSON encoded object with the column to sort on and the sort direction (eg. {\&quot;col\&quot;:\&quot;sales\&quot;,\&quot;dir\&quot;:\&quot;DESC\&quot;}) (required)
     * @param string[] $groupableColumns A JSON encoded array with the columns to group data on (eg. [\&quot;period\&quot;,\&quot;alias\&quot;]) (required)
     * @param \Swagger\Client\Model\Pagination $pagination A JSON encoded array with the columns to group data on (eg. [\&quot;period\&quot;,\&quot;alias\&quot;]) (required)
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @return \Swagger\Client\Model\SafecartCampaignGraphDatas
     */
    public function reportsPerformanceGraph($start, $end, $offerTypes, $categories, $aliases, $graphScale, $graphMetric, $sort, $groupableColumns, $pagination)
    {
        list($response) = $this->reportsPerformanceGraphWithHttpInfo($start, $end, $offerTypes, $categories, $aliases, $graphScale, $graphMetric, $sort, $groupableColumns, $pagination);
        return $response;
    }

    /**
     * Operation reportsPerformanceGraphWithHttpInfo
     *
     * 
     *
     * @param string $start Start date (YYYY-MM-DD) (required)
     * @param string $end End date (YYYY-MM-DD) (required)
     * @param string[] $offerTypes A JSON encoded array of offer types (eg [\&quot;download\&quot;,\&quot;lead\&quot;]) (required)
     * @param string[] $categories A JSON encoded array of offer categories (eg [\&quot;antimalware\&quot;,\&quot;drivers\&quot;]) (required)
     * @param string[] $aliases A JSON encoded array of alias IDs (eg [\&quot;1\&quot;,\&quot;2\&quot;]) (required)
     * @param string $graphScale The x-axis scale to use for graph data. Also defines the length of &#39;period&#39; when grouping on &#39;period&#39;. (required)
     * @param string[] $graphMetric The y-axis metrics to use for graph data. A JSON encoded array of one or two strings (eg. [\&quot;col1\&quot;,\&quot;col2\&quot;]) (required)
     * @param \Swagger\Client\Model\Sort1 $sort A JSON encoded object with the column to sort on and the sort direction (eg. {\&quot;col\&quot;:\&quot;sales\&quot;,\&quot;dir\&quot;:\&quot;DESC\&quot;}) (required)
     * @param string[] $groupableColumns A JSON encoded array with the columns to group data on (eg. [\&quot;period\&quot;,\&quot;alias\&quot;]) (required)
     * @param \Swagger\Client\Model\Pagination $pagination A JSON encoded array with the columns to group data on (eg. [\&quot;period\&quot;,\&quot;alias\&quot;]) (required)
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @return array of \Swagger\Client\Model\SafecartCampaignGraphDatas, HTTP status code, HTTP response headers (array of strings)
     */
    public function reportsPerformanceGraphWithHttpInfo($start, $end, $offerTypes, $categories, $aliases, $graphScale, $graphMetric, $sort, $groupableColumns, $pagination)
    {
        // verify the required parameter 'start' is set
        if ($start === null) {
            throw new \InvalidArgumentException('Missing the required parameter $start when calling reportsPerformanceGraph');
        }
        // verify the required parameter 'end' is set
        if ($end === null) {
            throw new \InvalidArgumentException('Missing the required parameter $end when calling reportsPerformanceGraph');
        }
        // verify the required parameter 'offerTypes' is set
        if ($offerTypes === null) {
            throw new \InvalidArgumentException('Missing the required parameter $offerTypes when calling reportsPerformanceGraph');
        }
        // verify the required parameter 'categories' is set
        if ($categories === null) {
            throw new \InvalidArgumentException('Missing the required parameter $categories when calling reportsPerformanceGraph');
        }
        // verify the required parameter 'aliases' is set
        if ($aliases === null) {
            throw new \InvalidArgumentException('Missing the required parameter $aliases when calling reportsPerformanceGraph');
        }
        // verify the required parameter 'graphScale' is set
        if ($graphScale === null) {
            throw new \InvalidArgumentException('Missing the required parameter $graphScale when calling reportsPerformanceGraph');
        }
        // verify the required parameter 'graphMetric' is set
        if ($graphMetric === null) {
            throw new \InvalidArgumentException('Missing the required parameter $graphMetric when calling reportsPerformanceGraph');
        }
        // verify the required parameter 'sort' is set
        if ($sort === null) {
            throw new \InvalidArgumentException('Missing the required parameter $sort when calling reportsPerformanceGraph');
        }
        // verify the required parameter 'groupableColumns' is set
        if ($groupableColumns === null) {
            throw new \InvalidArgumentException('Missing the required parameter $groupableColumns when calling reportsPerformanceGraph');
        }
        // verify the required parameter 'pagination' is set
        if ($pagination === null) {
            throw new \InvalidArgumentException('Missing the required parameter $pagination when calling reportsPerformanceGraph');
        }
        // parse inputs
        $resourcePath = "/reports/safecartcampaign/graph";
        $httpBody = '';
        $queryParams = [];
        $headerParams = [];
        $formParams = [];
        $_header_accept = $this->apiClient->selectHeaderAccept(['application/json']);
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(['application/json']);

        // query params
        if ($start !== null) {
            $queryParams['start'] = $this->apiClient->getSerializer()->toQueryValue($start);
        }
        // query params
        if ($end !== null) {
            $queryParams['end'] = $this->apiClient->getSerializer()->toQueryValue($end);
        }
        // query params
        if (is_array($offerTypes)) {
            $offerTypes = $this->apiClient->getSerializer()->serializeCollection($offerTypes, 'csv', true);
        }
        if ($offerTypes !== null) {
            $queryParams['offerTypes'] = $this->apiClient->getSerializer()->toQueryValue($offerTypes);
        }
        // query params
        if (is_array($categories)) {
            $categories = $this->apiClient->getSerializer()->serializeCollection($categories, 'csv', true);
        }
        if ($categories !== null) {
            $queryParams['categories'] = $this->apiClient->getSerializer()->toQueryValue($categories);
        }
        // query params
        if (is_array($aliases)) {
            $aliases = $this->apiClient->getSerializer()->serializeCollection($aliases, 'csv', true);
        }
        if ($aliases !== null) {
            $queryParams['aliases'] = $this->apiClient->getSerializer()->toQueryValue($aliases);
        }
        // query params
        if ($graphScale !== null) {
            $queryParams['graphScale'] = $this->apiClient->getSerializer()->toQueryValue($graphScale);
        }
        // query params
        if (is_array($graphMetric)) {
            $graphMetric = $this->apiClient->getSerializer()->serializeCollection($graphMetric, 'csv', true);
        }
        if ($graphMetric !== null) {
            $queryParams['graphMetric'] = $this->apiClient->getSerializer()->toQueryValue($graphMetric);
        }
        // query params
        if (is_array($groupableColumns)) {
            $groupableColumns = $this->apiClient->getSerializer()->serializeCollection($groupableColumns, 'csv', true);
        }
        if ($groupableColumns !== null) {
            $queryParams['groupableColumns'] = $this->apiClient->getSerializer()->toQueryValue($groupableColumns);
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        // body params
        $_tempBody = null;
        if (isset($sort)) {
            $_tempBody = $sort;
        }
// body params
        $_tempBody = null;
        if (isset($pagination)) {
            $_tempBody = $pagination;
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // this endpoint requires API key authentication
        $apiKey = $this->apiClient->getApiKeyWithPrefix('X-Authorization-JWT');
        if (strlen($apiKey) !== 0) {
            $headerParams['X-Authorization-JWT'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->apiClient->getApiKeyWithPrefix('X-API-KEY');
        if (strlen($apiKey) !== 0) {
            $headerParams['X-API-KEY'] = $apiKey;
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'GET',
                $queryParams,
                $httpBody,
                $headerParams,
                '\Swagger\Client\Model\SafecartCampaignGraphDatas',
                '/reports/safecartcampaign/graph'
            );

            return [$this->apiClient->getSerializer()->deserialize($response, '\Swagger\Client\Model\SafecartCampaignGraphDatas', $httpHeader), $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Swagger\Client\Model\SafecartCampaignGraphDatas', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Swagger\Client\Model\Error', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }

    /**
     * Operation reportsPerformanceSummary
     *
     * 
     *
     * @param string $startDate Start date (YYYY-MM-DD) (required)
     * @param string $endDate End date (YYYY-MM-DD) (required)
     * @param float $limit The number of results to return (optional)
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @return \Swagger\Client\Model\SafecartCampaignSummaryDatas
     */
    public function reportsPerformanceSummary($startDate, $endDate, $limit = null)
    {
        list($response) = $this->reportsPerformanceSummaryWithHttpInfo($startDate, $endDate, $limit);
        return $response;
    }

    /**
     * Operation reportsPerformanceSummaryWithHttpInfo
     *
     * 
     *
     * @param string $startDate Start date (YYYY-MM-DD) (required)
     * @param string $endDate End date (YYYY-MM-DD) (required)
     * @param float $limit The number of results to return (optional)
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @return array of \Swagger\Client\Model\SafecartCampaignSummaryDatas, HTTP status code, HTTP response headers (array of strings)
     */
    public function reportsPerformanceSummaryWithHttpInfo($startDate, $endDate, $limit = null)
    {
        // verify the required parameter 'startDate' is set
        if ($startDate === null) {
            throw new \InvalidArgumentException('Missing the required parameter $startDate when calling reportsPerformanceSummary');
        }
        // verify the required parameter 'endDate' is set
        if ($endDate === null) {
            throw new \InvalidArgumentException('Missing the required parameter $endDate when calling reportsPerformanceSummary');
        }
        // parse inputs
        $resourcePath = "/reports/safecartcampaign/summary";
        $httpBody = '';
        $queryParams = [];
        $headerParams = [];
        $formParams = [];
        $_header_accept = $this->apiClient->selectHeaderAccept(['application/json']);
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(['application/json']);

        // query params
        if ($startDate !== null) {
            $queryParams['startDate'] = $this->apiClient->getSerializer()->toQueryValue($startDate);
        }
        // query params
        if ($endDate !== null) {
            $queryParams['endDate'] = $this->apiClient->getSerializer()->toQueryValue($endDate);
        }
        // query params
        if ($limit !== null) {
            $queryParams['limit'] = $this->apiClient->getSerializer()->toQueryValue($limit);
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        
        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // this endpoint requires API key authentication
        $apiKey = $this->apiClient->getApiKeyWithPrefix('X-Authorization-JWT');
        if (strlen($apiKey) !== 0) {
            $headerParams['X-Authorization-JWT'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->apiClient->getApiKeyWithPrefix('X-API-KEY');
        if (strlen($apiKey) !== 0) {
            $headerParams['X-API-KEY'] = $apiKey;
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'GET',
                $queryParams,
                $httpBody,
                $headerParams,
                '\Swagger\Client\Model\SafecartCampaignSummaryDatas',
                '/reports/safecartcampaign/summary'
            );

            return [$this->apiClient->getSerializer()->deserialize($response, '\Swagger\Client\Model\SafecartCampaignSummaryDatas', $httpHeader), $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Swagger\Client\Model\SafecartCampaignSummaryDatas', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Swagger\Client\Model\Error', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }

    /**
     * Operation reportsPerformanceTotals
     *
     * 
     *
     * @param string $start Start date (YYYY-MM-DD) (required)
     * @param string $end End date (YYYY-MM-DD) (required)
     * @param string[] $offerTypes A JSON encoded array of offer types (eg [\&quot;download\&quot;,\&quot;lead\&quot;]) (required)
     * @param string[] $categories A JSON encoded array of offer categories (eg [\&quot;antimalware\&quot;,\&quot;drivers\&quot;]) (required)
     * @param string[] $aliases A JSON encoded array of alias IDs (eg [\&quot;1\&quot;,\&quot;2\&quot;]) (required)
     * @param string $graphScale The x-axis scale to use for graph data. Also defines the length of &#39;period&#39; when grouping on &#39;period&#39;. (required)
     * @param string[] $graphMetric The y-axis metrics to use for graph data. A JSON encoded array of one or two strings (eg. [\&quot;col1\&quot;,\&quot;col2\&quot;]) (required)
     * @param \Swagger\Client\Model\Sort1 $sort A JSON encoded object with the column to sort on and the sort direction (eg. {\&quot;col\&quot;:\&quot;sales\&quot;,\&quot;dir\&quot;:\&quot;DESC\&quot;}) (required)
     * @param string[] $groupableColumns A JSON encoded array with the columns to group data on (eg. [\&quot;period\&quot;,\&quot;alias\&quot;]) (required)
     * @param \Swagger\Client\Model\Pagination $pagination A JSON encoded array with the columns to group data on (eg. [\&quot;period\&quot;,\&quot;alias\&quot;]) (required)
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @return \Swagger\Client\Model\SafecartCampaignTotalsData
     */
    public function reportsPerformanceTotals($start, $end, $offerTypes, $categories, $aliases, $graphScale, $graphMetric, $sort, $groupableColumns, $pagination)
    {
        list($response) = $this->reportsPerformanceTotalsWithHttpInfo($start, $end, $offerTypes, $categories, $aliases, $graphScale, $graphMetric, $sort, $groupableColumns, $pagination);
        return $response;
    }

    /**
     * Operation reportsPerformanceTotalsWithHttpInfo
     *
     * 
     *
     * @param string $start Start date (YYYY-MM-DD) (required)
     * @param string $end End date (YYYY-MM-DD) (required)
     * @param string[] $offerTypes A JSON encoded array of offer types (eg [\&quot;download\&quot;,\&quot;lead\&quot;]) (required)
     * @param string[] $categories A JSON encoded array of offer categories (eg [\&quot;antimalware\&quot;,\&quot;drivers\&quot;]) (required)
     * @param string[] $aliases A JSON encoded array of alias IDs (eg [\&quot;1\&quot;,\&quot;2\&quot;]) (required)
     * @param string $graphScale The x-axis scale to use for graph data. Also defines the length of &#39;period&#39; when grouping on &#39;period&#39;. (required)
     * @param string[] $graphMetric The y-axis metrics to use for graph data. A JSON encoded array of one or two strings (eg. [\&quot;col1\&quot;,\&quot;col2\&quot;]) (required)
     * @param \Swagger\Client\Model\Sort1 $sort A JSON encoded object with the column to sort on and the sort direction (eg. {\&quot;col\&quot;:\&quot;sales\&quot;,\&quot;dir\&quot;:\&quot;DESC\&quot;}) (required)
     * @param string[] $groupableColumns A JSON encoded array with the columns to group data on (eg. [\&quot;period\&quot;,\&quot;alias\&quot;]) (required)
     * @param \Swagger\Client\Model\Pagination $pagination A JSON encoded array with the columns to group data on (eg. [\&quot;period\&quot;,\&quot;alias\&quot;]) (required)
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @return array of \Swagger\Client\Model\SafecartCampaignTotalsData, HTTP status code, HTTP response headers (array of strings)
     */
    public function reportsPerformanceTotalsWithHttpInfo($start, $end, $offerTypes, $categories, $aliases, $graphScale, $graphMetric, $sort, $groupableColumns, $pagination)
    {
        // verify the required parameter 'start' is set
        if ($start === null) {
            throw new \InvalidArgumentException('Missing the required parameter $start when calling reportsPerformanceTotals');
        }
        // verify the required parameter 'end' is set
        if ($end === null) {
            throw new \InvalidArgumentException('Missing the required parameter $end when calling reportsPerformanceTotals');
        }
        // verify the required parameter 'offerTypes' is set
        if ($offerTypes === null) {
            throw new \InvalidArgumentException('Missing the required parameter $offerTypes when calling reportsPerformanceTotals');
        }
        // verify the required parameter 'categories' is set
        if ($categories === null) {
            throw new \InvalidArgumentException('Missing the required parameter $categories when calling reportsPerformanceTotals');
        }
        // verify the required parameter 'aliases' is set
        if ($aliases === null) {
            throw new \InvalidArgumentException('Missing the required parameter $aliases when calling reportsPerformanceTotals');
        }
        // verify the required parameter 'graphScale' is set
        if ($graphScale === null) {
            throw new \InvalidArgumentException('Missing the required parameter $graphScale when calling reportsPerformanceTotals');
        }
        // verify the required parameter 'graphMetric' is set
        if ($graphMetric === null) {
            throw new \InvalidArgumentException('Missing the required parameter $graphMetric when calling reportsPerformanceTotals');
        }
        // verify the required parameter 'sort' is set
        if ($sort === null) {
            throw new \InvalidArgumentException('Missing the required parameter $sort when calling reportsPerformanceTotals');
        }
        // verify the required parameter 'groupableColumns' is set
        if ($groupableColumns === null) {
            throw new \InvalidArgumentException('Missing the required parameter $groupableColumns when calling reportsPerformanceTotals');
        }
        // verify the required parameter 'pagination' is set
        if ($pagination === null) {
            throw new \InvalidArgumentException('Missing the required parameter $pagination when calling reportsPerformanceTotals');
        }
        // parse inputs
        $resourcePath = "/reports/safecartcampaign/totals";
        $httpBody = '';
        $queryParams = [];
        $headerParams = [];
        $formParams = [];
        $_header_accept = $this->apiClient->selectHeaderAccept(['application/json']);
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(['application/json']);

        // query params
        if ($start !== null) {
            $queryParams['start'] = $this->apiClient->getSerializer()->toQueryValue($start);
        }
        // query params
        if ($end !== null) {
            $queryParams['end'] = $this->apiClient->getSerializer()->toQueryValue($end);
        }
        // query params
        if (is_array($offerTypes)) {
            $offerTypes = $this->apiClient->getSerializer()->serializeCollection($offerTypes, 'csv', true);
        }
        if ($offerTypes !== null) {
            $queryParams['offerTypes'] = $this->apiClient->getSerializer()->toQueryValue($offerTypes);
        }
        // query params
        if (is_array($categories)) {
            $categories = $this->apiClient->getSerializer()->serializeCollection($categories, 'csv', true);
        }
        if ($categories !== null) {
            $queryParams['categories'] = $this->apiClient->getSerializer()->toQueryValue($categories);
        }
        // query params
        if (is_array($aliases)) {
            $aliases = $this->apiClient->getSerializer()->serializeCollection($aliases, 'csv', true);
        }
        if ($aliases !== null) {
            $queryParams['aliases'] = $this->apiClient->getSerializer()->toQueryValue($aliases);
        }
        // query params
        if ($graphScale !== null) {
            $queryParams['graphScale'] = $this->apiClient->getSerializer()->toQueryValue($graphScale);
        }
        // query params
        if (is_array($graphMetric)) {
            $graphMetric = $this->apiClient->getSerializer()->serializeCollection($graphMetric, 'csv', true);
        }
        if ($graphMetric !== null) {
            $queryParams['graphMetric'] = $this->apiClient->getSerializer()->toQueryValue($graphMetric);
        }
        // query params
        if (is_array($groupableColumns)) {
            $groupableColumns = $this->apiClient->getSerializer()->serializeCollection($groupableColumns, 'csv', true);
        }
        if ($groupableColumns !== null) {
            $queryParams['groupableColumns'] = $this->apiClient->getSerializer()->toQueryValue($groupableColumns);
        }
        // default format to json
        $resourcePath = str_replace("{format}", "json", $resourcePath);

        // body params
        $_tempBody = null;
        if (isset($sort)) {
            $_tempBody = $sort;
        }
// body params
        $_tempBody = null;
        if (isset($pagination)) {
            $_tempBody = $pagination;
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            $httpBody = $_tempBody; // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = $formParams; // for HTTP post (form)
        }
        // this endpoint requires API key authentication
        $apiKey = $this->apiClient->getApiKeyWithPrefix('X-Authorization-JWT');
        if (strlen($apiKey) !== 0) {
            $headerParams['X-Authorization-JWT'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->apiClient->getApiKeyWithPrefix('X-API-KEY');
        if (strlen($apiKey) !== 0) {
            $headerParams['X-API-KEY'] = $apiKey;
        }
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi(
                $resourcePath,
                'GET',
                $queryParams,
                $httpBody,
                $headerParams,
                '\Swagger\Client\Model\SafecartCampaignTotalsData',
                '/reports/safecartcampaign/totals'
            );

            return [$this->apiClient->getSerializer()->deserialize($response, '\Swagger\Client\Model\SafecartCampaignTotalsData', $httpHeader), $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Swagger\Client\Model\SafecartCampaignTotalsData', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Swagger\Client\Model\Error', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }

            throw $e;
        }
    }
}
